{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPAwCnmVZfzIYdFcRl9riFx",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/gianlinhares/PrimeiroProjetoAlura/blob/master/AulasPython.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "Criação de App: para testar funções, variáveis e laços"
      ],
      "metadata": {
        "id": "sgnPMh7els51"
      }
    },
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "0zNVAd4-lJNs",
        "outputId": "e5d92f0e-8ba8-4f74-92d0-639a484ef9f7"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "\n",
            "░██████╗░█████╗░██████╗░░█████╗░██████╗░  ███████╗██╗░░██╗██████╗░██████╗░███████╗░██████╗░██████╗\n",
            "██╔════╝██╔══██╗██╔══██╗██╔══██╗██╔══██╗  ██╔════╝╚██╗██╔╝██╔══██╗██╔══██╗██╔════╝██╔════╝██╔════╝\n",
            "╚█████╗░███████║██████╦╝██║░░██║██████╔╝  █████╗░░░╚███╔╝░██████╔╝██████╔╝█████╗░░╚█████╗░╚█████╗░\n",
            "░╚═══██╗██╔══██║██╔══██╗██║░░██║██╔══██╗  ██╔══╝░░░██╔██╗░██╔═══╝░██╔══██╗██╔══╝░░░╚═══██╗░╚═══██╗\n",
            "██████╔╝██║░░██║██████╦╝╚█████╔╝██║░░██║  ███████╗██╔╝╚██╗██║░░░░░██║░░██║███████╗██████╔╝██████╔╝\n",
            "╚═════╝░╚═╝░░╚═╝╚═════╝░░╚════╝░╚═╝░░╚═╝  ╚══════╝╚═╝░░╚═╝╚═╝░░░░░╚═╝░░╚═╝╚══════╝╚═════╝░╚═════╝░\n",
            "      \n",
            "============================= Bem-vindo ao Sabor Express! =======================================\n",
            "\n",
            "1. Cadastrar restaurante\n",
            "2. Listar restaurantes\n",
            "3. Ativar restaurante\n",
            "4. Sair\n",
            "Escolha uma opção: 2\n",
            "Restaurantes cadastrados:\n",
            "\n",
            "Nome do Restaurante            CategoriaSituação            \n",
            "Subway                         Fast Food Inativo            \n",
            "McDonald's                     Fast Food  Ativo             \n",
            "Burger King                    Fast Food Inativo            \n",
            "Minato                             Sushi Inativo            \n",
            "Digite qualquer tecla para voltar ao menu principal.\n",
            "\n",
            "\n",
            "░██████╗░█████╗░██████╗░░█████╗░██████╗░  ███████╗██╗░░██╗██████╗░██████╗░███████╗░██████╗░██████╗\n",
            "██╔════╝██╔══██╗██╔══██╗██╔══██╗██╔══██╗  ██╔════╝╚██╗██╔╝██╔══██╗██╔══██╗██╔════╝██╔════╝██╔════╝\n",
            "╚█████╗░███████║██████╦╝██║░░██║██████╔╝  █████╗░░░╚███╔╝░██████╔╝██████╔╝█████╗░░╚█████╗░╚█████╗░\n",
            "░╚═══██╗██╔══██║██╔══██╗██║░░██║██╔══██╗  ██╔══╝░░░██╔██╗░██╔═══╝░██╔══██╗██╔══╝░░░╚═══██╗░╚═══██╗\n",
            "██████╔╝██║░░██║██████╦╝╚█████╔╝██║░░██║  ███████╗██╔╝╚██╗██║░░░░░██║░░██║███████╗██████╔╝██████╔╝\n",
            "╚═════╝░╚═╝░░╚═╝╚═════╝░░╚════╝░╚═╝░░╚═╝  ╚══════╝╚═╝░░╚═╝╚═╝░░░░░╚═╝░░╚═╝╚══════╝╚═════╝░╚═════╝░\n",
            "      \n",
            "============================= Bem-vindo ao Sabor Express! =======================================\n",
            "\n",
            "1. Cadastrar restaurante\n",
            "2. Listar restaurantes\n",
            "3. Ativar restaurante\n",
            "4. Sair\n",
            "Escolha uma opção: 2\n",
            "Restaurantes cadastrados:\n",
            "\n",
            "Nome do Restaurante            CategoriaSituação            \n",
            "Subway                         Fast Food Inativo            \n",
            "McDonald's                     Fast Food  Ativo             \n",
            "Burger King                    Fast Food Inativo            \n",
            "Minato                             Sushi Inativo            \n",
            "Digite qualquer tecla para voltar ao menu principal.1\n",
            "\n",
            "\n",
            "░██████╗░█████╗░██████╗░░█████╗░██████╗░  ███████╗██╗░░██╗██████╗░██████╗░███████╗░██████╗░██████╗\n",
            "██╔════╝██╔══██╗██╔══██╗██╔══██╗██╔══██╗  ██╔════╝╚██╗██╔╝██╔══██╗██╔══██╗██╔════╝██╔════╝██╔════╝\n",
            "╚█████╗░███████║██████╦╝██║░░██║██████╔╝  █████╗░░░╚███╔╝░██████╔╝██████╔╝█████╗░░╚█████╗░╚█████╗░\n",
            "░╚═══██╗██╔══██║██╔══██╗██║░░██║██╔══██╗  ██╔══╝░░░██╔██╗░██╔═══╝░██╔══██╗██╔══╝░░░╚═══██╗░╚═══██╗\n",
            "██████╔╝██║░░██║██████╦╝╚█████╔╝██║░░██║  ███████╗██╔╝╚██╗██║░░░░░██║░░██║███████╗██████╔╝██████╔╝\n",
            "╚═════╝░╚═╝░░╚═╝╚═════╝░░╚════╝░╚═╝░░╚═╝  ╚══════╝╚═╝░░╚═╝╚═╝░░░░░╚═╝░░╚═╝╚══════╝╚═════╝░╚═════╝░\n",
            "      \n",
            "============================= Bem-vindo ao Sabor Express! =======================================\n",
            "\n",
            "1. Cadastrar restaurante\n",
            "2. Listar restaurantes\n",
            "3. Ativar restaurante\n",
            "4. Sair\n",
            "Escolha uma opção: 4\n",
            "Encerrando o programa...\n",
            "Obrigado por usar o Sabor Express! Até a próxima.\n"
          ]
        }
      ],
      "source": [
        "import os\n",
        "\n",
        "restaurantes = [{'nome': 'Subway', 'categoria': 'Fast Food', 'ativo': False},\n",
        "                {'nome': 'McDonald\\'s', 'categoria': 'Fast Food', 'ativo': True},\n",
        "                {'nome': 'Burger King', 'categoria': 'Fast Food', 'ativo': False},\n",
        "                {'nome': 'Minato', 'categoria': 'Sushi', 'ativo': False}]\n",
        "\n",
        "def limpar_tela():\n",
        "    os.system('cls' if os.name == 'nt' else 'clear')\n",
        "\n",
        "def exibir_nome_do_app():\n",
        "    print(\"\"\"\n",
        "\n",
        "░██████╗░█████╗░██████╗░░█████╗░██████╗░  ███████╗██╗░░██╗██████╗░██████╗░███████╗░██████╗░██████╗\n",
        "██╔════╝██╔══██╗██╔══██╗██╔══██╗██╔══██╗  ██╔════╝╚██╗██╔╝██╔══██╗██╔══██╗██╔════╝██╔════╝██╔════╝\n",
        "╚█████╗░███████║██████╦╝██║░░██║██████╔╝  █████╗░░░╚███╔╝░██████╔╝██████╔╝█████╗░░╚█████╗░╚█████╗░\n",
        "░╚═══██╗██╔══██║██╔══██╗██║░░██║██╔══██╗  ██╔══╝░░░██╔██╗░██╔═══╝░██╔══██╗██╔══╝░░░╚═══██╗░╚═══██╗\n",
        "██████╔╝██║░░██║██████╦╝╚█████╔╝██║░░██║  ███████╗██╔╝╚██╗██║░░░░░██║░░██║███████╗██████╔╝██████╔╝\n",
        "╚═════╝░╚═╝░░╚═╝╚═════╝░░╚════╝░╚═╝░░╚═╝  ╚══════╝╚═╝░░╚═╝╚═╝░░░░░╚═╝░░╚═╝╚══════╝╚═════╝░╚═════╝░\n",
        "      \"\"\")\n",
        "\n",
        "def voltar_ao_menu():\n",
        "    input('Digite qualquer tecla para voltar ao menu principal.')\n",
        "    main()\n",
        "\n",
        "def exibir_menu():\n",
        "    print('============================= Bem-vindo ao Sabor Express! =======================================\\n')\n",
        "    print('1. Cadastrar restaurante')\n",
        "    print('2. Listar restaurantes')\n",
        "    print('3. Ativar restaurante')\n",
        "    print('4. Sair')\n",
        "\n",
        "def opcao_invalida():\n",
        "    print('Opção inválida. ')\n",
        "    voltar_ao_menu()\n",
        "\n",
        "def cadastrar_novo_restaurante():\n",
        "    limpar_tela()\n",
        "    nome_do_restaurante = input('Digite o nome do restaurante que deseja cadastrar: ')\n",
        "    categoria_do_restaurante = input(f'Digite a categoria do restaurante {nome_do_restaurante} (ex: Fast Food, Japonês, etc): ')\n",
        "    restaurantes.append({'nome': nome_do_restaurante, 'categoria': categoria_do_restaurante, 'ativo': False})\n",
        "    print(f'Restaurante \"{nome_do_restaurante}\" cadastrado com sucesso!\\n')\n",
        "    voltar_ao_menu()\n",
        "\n",
        "def listar_restaurantes():\n",
        "    limpar_tela()\n",
        "    if not restaurantes:\n",
        "        print('Nenhum restaurante cadastrado.\\n')\n",
        "    else:\n",
        "        print('Restaurantes cadastrados:\\n')\n",
        "\n",
        "        print('Nome do Restaurante'.ljust(20) + 'Categoria'.rjust(20) + 'Situação'.ljust(20))\n",
        "        for restaurante in restaurantes:\n",
        "            nome_restaurante = restaurante['nome']\n",
        "            categoria_restaurante = restaurante['categoria']\n",
        "            ativo_restaurante = '  Ativo' if restaurante['ativo'] else ' Inativo'\n",
        "            print(f'{nome_restaurante.ljust(20)}{categoria_restaurante.rjust(20)}{ativo_restaurante.ljust(20)}')\n",
        "    voltar_ao_menu()\n",
        "\n",
        "def ativar_restaurante():\n",
        "    limpar_tela()\n",
        "    nome_do_restaurante = input('Digite o nome do restaurante que deseja ativar: ')\n",
        "    for restaurante in restaurantes:\n",
        "        if restaurante['nome'].lower() == nome_do_restaurante.lower():\n",
        "            restaurante['ativo'] = not restaurante['ativo']\n",
        "            estado = 'ativado' if restaurante['ativo'] else 'desativado'\n",
        "            print(f'Restaurante \"{nome_do_restaurante}\" {estado} com sucesso!\\n')\n",
        "            break\n",
        "    else:\n",
        "        print(f'Restaurante \"{nome_do_restaurante}\" não encontrado.\\n')\n",
        "    voltar_ao_menu()\n",
        "\n",
        "def finalizar_app():\n",
        "    limpar_tela()\n",
        "    print('Encerrando o programa...')\n",
        "    print('Obrigado por usar o Sabor Express! Até a próxima.')\n",
        "\n",
        "def escolher_opcao():\n",
        "    try:\n",
        "        opcao_escolhida = int(input('Escolha uma opção: '))\n",
        "\n",
        "        match opcao_escolhida:\n",
        "            case 1: cadastrar_novo_restaurante()\n",
        "            case 2: listar_restaurantes()\n",
        "            case 3: ativar_restaurante()\n",
        "            case 4: finalizar_app()\n",
        "            case _: opcao_invalida()\n",
        "    except:\n",
        "        opcao_invalida()\n",
        "\n",
        "def main():\n",
        "    limpar_tela()\n",
        "    exibir_nome_do_app()\n",
        "    exibir_menu()\n",
        "    escolher_opcao()\n",
        "\n",
        "if __name__ == '__main__':\n",
        "    main()"
      ]
    }
  ]
}